# spot-cluster.yaml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

managedNodeGroups:
- name: spot
  instanceTypes: ["c5.large","m5a.large","m5.large","t3.large","t3.medium","c5a.large"]
  spot: false
  desiredCapacity: 2
    